version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/express-app
hook:
  ApplicaionStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: /home/ec2-user/express-app
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: /home/ec2-user/express-app
  ApplicaionStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user